export const LOADING_FACTS = [
  "Grover's algorithm finds a marked item using about the square root of the oracle calls required by an unstructured classical search.",
  "A qubit can carry relative phase information even when a measurement ultimately returns only a classical bit.",
  "Quantum interference lets algorithms amplify useful paths while suppressing unwanted ones.",
  "The no-cloning theorem prevents an unknown quantum state from being copied perfectly.",
  "Quantum teleportation transfers a state, not matter, and still requires ordinary classical communication.",
  "Entanglement creates correlations that cannot be reproduced by assigning each particle independent local properties.",
  "A quantum oracle is a reversible circuit representation of the question an algorithm asks.",
  "Most quantum speedups depend as much on careful problem encoding as on the quantum circuit itself.",
  "Measurement shots sample a quantum probability distribution; they do not reveal a hidden wavefunction directly.",
  "Quantum error correction protects logical information by spreading it across many physical qubits.",
  "A global phase cannot be measured, but relative phases can change interference outcomes.",
  "Reversible quantum gates preserve information, unlike ordinary irreversible operations such as erasing a bit.",
  "The Bloch sphere describes one qubit, but there is no equally simple three-dimensional picture for many entangled qubits.",
  "Grover amplification rotates a state toward marked solutions rather than checking database rows one by one.",
  "Circuit depth can matter as much as qubit count because noise accumulates while gates execute.",
  "DNA in one human cell would stretch to roughly two metres if fully extended.",
  "Only a small fraction of the human genome directly encodes proteins; much of the rest regulates, structures, or transcribes non-coding RNA.",
  "The two DNA strands are antiparallel: one runs 5-prime to 3-prime while its partner runs 3-prime to 5-prime.",
  "A reverse complement is not the same as reversing a sequence; every base must also be complemented.",
  "DNA polymerases synthesize new DNA only in the 5-prime to 3-prime direction.",
  "Telomeres protect chromosome ends from being mistaken for broken DNA.",
  "Mitochondrial DNA is inherited separately from most nuclear DNA and exists in many copies per cell.",
  "A single human genome differs from another at millions of positions, while the overwhelming majority of bases are shared.",
  "Codons are read in groups of three bases, so changing a reading frame can alter every downstream amino acid.",
  "Some DNA changes are silent because multiple codons can encode the same amino acid.",
  "Ambiguous IUPAC symbols preserve uncertainty: N means any base, while R means A or G.",
  "GC-rich DNA generally has a higher melting temperature than equally long AT-rich DNA.",
  "Bacterial genomes are often circular, but many bacteria also carry smaller independently replicating plasmids.",
  "Escherichia coli can copy its chromosome while a previous round of replication is still in progress.",
  "CRISPR systems evolved as microbial defenses that retain molecular memories of earlier genetic invaders.",
  "A FASTA header is metadata; the biological sequence begins on the following lines.",
  "An accession version such as U00096.3 identifies both a record and a particular revision of that record.",
  "NCBI taxonomy IDs are stable numerical identifiers that avoid ambiguity between common organism names.",
  "GenBank and RefSeq may describe related sequences, but RefSeq records are curated reference representations.",
  "An assembly accession beginning GCF_ denotes RefSeq, while GCA_ denotes GenBank.",
  "Sequence alignment and exact substring search answer different questions: similarity does not guarantee an exact occurrence.",
  "A sliding-window search can inspect a genome locally without loading an entire chromosome into one quantum circuit.",
  "Window stride trades positional resolution for fewer comparisons: a larger stride skips more possible starts.",
  "Searching both strands matters because a biological motif may occur as its reverse complement.",
  "An exact-match oracle with mismatch threshold zero cannot treat a one-base variant as a hit.",
  "Similarity scores produced from quantum-state angles are not automatically equivalent to biological percent identity.",
  "Shot noise decreases gradually; multiplying the number of measurements does not multiply precision at the same rate.",
  "Classical validation is valuable in quantum experiments because it checks whether amplified candidates are biologically correct.",
  "The lacZ gene became a foundational molecular-biology reporter because its activity can produce an easily visible color change.",
  "BRCA1 participates in DNA-damage repair and genome stability rather than acting as a simple on/off cancer switch.",
  "Rice has been a major comparative-genomics model because its genome is relatively compact among cereal crops.",
  "House mice and closely related Mus species help researchers compare how genomes diverge over evolutionary time.",
  "A nucleotide record can describe genomic DNA, a transcript, or another molecule; the accession alone does not prove its analysis type.",
  "Caching metadata and images improves responsiveness, but sequence records should still retain provenance and version information.",
  "The fastest scientific interface is not the one with no waiting; it is the one that makes progress, limits, and next actions understandable.",
] as const;
