/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuantumSearchResultsRouteImport } from './routes/quantum-search-results'
import { Route as QuantumSearchRouteImport } from './routes/quantum-search'
import { Route as QuantumHardwareResultsRouteImport } from './routes/quantum-hardware-results'
import { Route as QmlRouteImport } from './routes/qml'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QmlIndexRouteImport } from './routes/qml.index'
import { Route as QmlResultsRouteImport } from './routes/qml.results'
import { Route as QmlImagingRouteImport } from './routes/qml.imaging'
import { Route as QmlEvidenceRouteImport } from './routes/qml.evidence'
import { Route as QmlAnalyzeRouteImport } from './routes/qml.analyze'
import { Route as NcbiSearchRouteImport } from './routes/ncbi.search'
import { Route as QmlModelsModelIdRouteImport } from './routes/qml.models.$modelId'
import { Route as QmlGenomicsFhRouteImport } from './routes/qml.genomics.fh'
import { Route as NcbiRecordAccessionRouteImport } from './routes/ncbi.record.$accession'
import { Route as NcbiOrganismTaxIdRouteImport } from './routes/ncbi.organism.$taxId'

const QuantumSearchResultsRoute = QuantumSearchResultsRouteImport.update({
  id: '/quantum-search-results',
  path: '/quantum-search-results',
  getParentRoute: () => rootRouteImport,
} as any)
const QuantumSearchRoute = QuantumSearchRouteImport.update({
  id: '/quantum-search',
  path: '/quantum-search',
  getParentRoute: () => rootRouteImport,
} as any)
const QuantumHardwareResultsRoute = QuantumHardwareResultsRouteImport.update({
  id: '/quantum-hardware-results',
  path: '/quantum-hardware-results',
  getParentRoute: () => rootRouteImport,
} as any)
const QmlRoute = QmlRouteImport.update({
  id: '/qml',
  path: '/qml',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QmlIndexRoute = QmlIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => QmlRoute,
} as any)
const QmlResultsRoute = QmlResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => QmlRoute,
} as any)
const QmlImagingRoute = QmlImagingRouteImport.update({
  id: '/imaging',
  path: '/imaging',
  getParentRoute: () => QmlRoute,
} as any)
const QmlEvidenceRoute = QmlEvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => QmlRoute,
} as any)
const QmlAnalyzeRoute = QmlAnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => QmlRoute,
} as any)
const NcbiSearchRoute = NcbiSearchRouteImport.update({
  id: '/ncbi/search',
  path: '/ncbi/search',
  getParentRoute: () => rootRouteImport,
} as any)
const QmlModelsModelIdRoute = QmlModelsModelIdRouteImport.update({
  id: '/models/$modelId',
  path: '/models/$modelId',
  getParentRoute: () => QmlRoute,
} as any)
const QmlGenomicsFhRoute = QmlGenomicsFhRouteImport.update({
  id: '/genomics/fh',
  path: '/genomics/fh',
  getParentRoute: () => QmlRoute,
} as any)
const NcbiRecordAccessionRoute = NcbiRecordAccessionRouteImport.update({
  id: '/ncbi/record/$accession',
  path: '/ncbi/record/$accession',
  getParentRoute: () => rootRouteImport,
} as any)
const NcbiOrganismTaxIdRoute = NcbiOrganismTaxIdRouteImport.update({
  id: '/ncbi/organism/$taxId',
  path: '/ncbi/organism/$taxId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/qml': typeof QmlRouteWithChildren
  '/quantum-hardware-results': typeof QuantumHardwareResultsRoute
  '/quantum-search': typeof QuantumSearchRoute
  '/quantum-search-results': typeof QuantumSearchResultsRoute
  '/ncbi/search': typeof NcbiSearchRoute
  '/qml/analyze': typeof QmlAnalyzeRoute
  '/qml/evidence': typeof QmlEvidenceRoute
  '/qml/imaging': typeof QmlImagingRoute
  '/qml/results': typeof QmlResultsRoute
  '/qml/': typeof QmlIndexRoute
  '/ncbi/organism/$taxId': typeof NcbiOrganismTaxIdRoute
  '/ncbi/record/$accession': typeof NcbiRecordAccessionRoute
  '/qml/genomics/fh': typeof QmlGenomicsFhRoute
  '/qml/models/$modelId': typeof QmlModelsModelIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/quantum-hardware-results': typeof QuantumHardwareResultsRoute
  '/quantum-search': typeof QuantumSearchRoute
  '/quantum-search-results': typeof QuantumSearchResultsRoute
  '/ncbi/search': typeof NcbiSearchRoute
  '/qml/analyze': typeof QmlAnalyzeRoute
  '/qml/evidence': typeof QmlEvidenceRoute
  '/qml/imaging': typeof QmlImagingRoute
  '/qml/results': typeof QmlResultsRoute
  '/qml': typeof QmlIndexRoute
  '/ncbi/organism/$taxId': typeof NcbiOrganismTaxIdRoute
  '/ncbi/record/$accession': typeof NcbiRecordAccessionRoute
  '/qml/genomics/fh': typeof QmlGenomicsFhRoute
  '/qml/models/$modelId': typeof QmlModelsModelIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/qml': typeof QmlRouteWithChildren
  '/quantum-hardware-results': typeof QuantumHardwareResultsRoute
  '/quantum-search': typeof QuantumSearchRoute
  '/quantum-search-results': typeof QuantumSearchResultsRoute
  '/ncbi/search': typeof NcbiSearchRoute
  '/qml/analyze': typeof QmlAnalyzeRoute
  '/qml/evidence': typeof QmlEvidenceRoute
  '/qml/imaging': typeof QmlImagingRoute
  '/qml/results': typeof QmlResultsRoute
  '/qml/': typeof QmlIndexRoute
  '/ncbi/organism/$taxId': typeof NcbiOrganismTaxIdRoute
  '/ncbi/record/$accession': typeof NcbiRecordAccessionRoute
  '/qml/genomics/fh': typeof QmlGenomicsFhRoute
  '/qml/models/$modelId': typeof QmlModelsModelIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/qml'
    | '/quantum-hardware-results'
    | '/quantum-search'
    | '/quantum-search-results'
    | '/ncbi/search'
    | '/qml/analyze'
    | '/qml/evidence'
    | '/qml/imaging'
    | '/qml/results'
    | '/qml/'
    | '/ncbi/organism/$taxId'
    | '/ncbi/record/$accession'
    | '/qml/genomics/fh'
    | '/qml/models/$modelId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/quantum-hardware-results'
    | '/quantum-search'
    | '/quantum-search-results'
    | '/ncbi/search'
    | '/qml/analyze'
    | '/qml/evidence'
    | '/qml/imaging'
    | '/qml/results'
    | '/qml'
    | '/ncbi/organism/$taxId'
    | '/ncbi/record/$accession'
    | '/qml/genomics/fh'
    | '/qml/models/$modelId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/qml'
    | '/quantum-hardware-results'
    | '/quantum-search'
    | '/quantum-search-results'
    | '/ncbi/search'
    | '/qml/analyze'
    | '/qml/evidence'
    | '/qml/imaging'
    | '/qml/results'
    | '/qml/'
    | '/ncbi/organism/$taxId'
    | '/ncbi/record/$accession'
    | '/qml/genomics/fh'
    | '/qml/models/$modelId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  QmlRoute: typeof QmlRouteWithChildren
  QuantumHardwareResultsRoute: typeof QuantumHardwareResultsRoute
  QuantumSearchRoute: typeof QuantumSearchRoute
  QuantumSearchResultsRoute: typeof QuantumSearchResultsRoute
  NcbiSearchRoute: typeof NcbiSearchRoute
  NcbiOrganismTaxIdRoute: typeof NcbiOrganismTaxIdRoute
  NcbiRecordAccessionRoute: typeof NcbiRecordAccessionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quantum-search-results': {
      id: '/quantum-search-results'
      path: '/quantum-search-results'
      fullPath: '/quantum-search-results'
      preLoaderRoute: typeof QuantumSearchResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quantum-search': {
      id: '/quantum-search'
      path: '/quantum-search'
      fullPath: '/quantum-search'
      preLoaderRoute: typeof QuantumSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quantum-hardware-results': {
      id: '/quantum-hardware-results'
      path: '/quantum-hardware-results'
      fullPath: '/quantum-hardware-results'
      preLoaderRoute: typeof QuantumHardwareResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qml': {
      id: '/qml'
      path: '/qml'
      fullPath: '/qml'
      preLoaderRoute: typeof QmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qml/': {
      id: '/qml/'
      path: '/'
      fullPath: '/qml/'
      preLoaderRoute: typeof QmlIndexRouteImport
      parentRoute: typeof QmlRoute
    }
    '/qml/results': {
      id: '/qml/results'
      path: '/results'
      fullPath: '/qml/results'
      preLoaderRoute: typeof QmlResultsRouteImport
      parentRoute: typeof QmlRoute
    }
    '/qml/imaging': {
      id: '/qml/imaging'
      path: '/imaging'
      fullPath: '/qml/imaging'
      preLoaderRoute: typeof QmlImagingRouteImport
      parentRoute: typeof QmlRoute
    }
    '/qml/evidence': {
      id: '/qml/evidence'
      path: '/evidence'
      fullPath: '/qml/evidence'
      preLoaderRoute: typeof QmlEvidenceRouteImport
      parentRoute: typeof QmlRoute
    }
    '/qml/analyze': {
      id: '/qml/analyze'
      path: '/analyze'
      fullPath: '/qml/analyze'
      preLoaderRoute: typeof QmlAnalyzeRouteImport
      parentRoute: typeof QmlRoute
    }
    '/ncbi/search': {
      id: '/ncbi/search'
      path: '/ncbi/search'
      fullPath: '/ncbi/search'
      preLoaderRoute: typeof NcbiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qml/models/$modelId': {
      id: '/qml/models/$modelId'
      path: '/models/$modelId'
      fullPath: '/qml/models/$modelId'
      preLoaderRoute: typeof QmlModelsModelIdRouteImport
      parentRoute: typeof QmlRoute
    }
    '/qml/genomics/fh': {
      id: '/qml/genomics/fh'
      path: '/genomics/fh'
      fullPath: '/qml/genomics/fh'
      preLoaderRoute: typeof QmlGenomicsFhRouteImport
      parentRoute: typeof QmlRoute
    }
    '/ncbi/record/$accession': {
      id: '/ncbi/record/$accession'
      path: '/ncbi/record/$accession'
      fullPath: '/ncbi/record/$accession'
      preLoaderRoute: typeof NcbiRecordAccessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ncbi/organism/$taxId': {
      id: '/ncbi/organism/$taxId'
      path: '/ncbi/organism/$taxId'
      fullPath: '/ncbi/organism/$taxId'
      preLoaderRoute: typeof NcbiOrganismTaxIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface QmlRouteChildren {
  QmlAnalyzeRoute: typeof QmlAnalyzeRoute
  QmlEvidenceRoute: typeof QmlEvidenceRoute
  QmlImagingRoute: typeof QmlImagingRoute
  QmlResultsRoute: typeof QmlResultsRoute
  QmlIndexRoute: typeof QmlIndexRoute
  QmlGenomicsFhRoute: typeof QmlGenomicsFhRoute
  QmlModelsModelIdRoute: typeof QmlModelsModelIdRoute
}

const QmlRouteChildren: QmlRouteChildren = {
  QmlAnalyzeRoute: QmlAnalyzeRoute,
  QmlEvidenceRoute: QmlEvidenceRoute,
  QmlImagingRoute: QmlImagingRoute,
  QmlResultsRoute: QmlResultsRoute,
  QmlIndexRoute: QmlIndexRoute,
  QmlGenomicsFhRoute: QmlGenomicsFhRoute,
  QmlModelsModelIdRoute: QmlModelsModelIdRoute,
}

const QmlRouteWithChildren = QmlRoute._addFileChildren(QmlRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  QmlRoute: QmlRouteWithChildren,
  QuantumHardwareResultsRoute: QuantumHardwareResultsRoute,
  QuantumSearchRoute: QuantumSearchRoute,
  QuantumSearchResultsRoute: QuantumSearchResultsRoute,
  NcbiSearchRoute: NcbiSearchRoute,
  NcbiOrganismTaxIdRoute: NcbiOrganismTaxIdRoute,
  NcbiRecordAccessionRoute: NcbiRecordAccessionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
